# ------------------------------------------------------------
# Pre-commit Hooks for Running-Agent Project
# ------------------------------------------------------------
# Tools:
#   - Ruff (lint + format)
#   - Mypy (type checking)
#   - Pytest (unit tests)
#   - Hygiene (YAML, EOF, trailing spaces)
# ------------------------------------------------------------

repos:
  # 1) Ruff — Linting + auto-fix + formatting
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.6.9
    hooks:
      - id: ruff
        name: ruff (lint)
        args: ["--fix"]
      - id: ruff-format
        name: ruff-format

  # 2) Mypy — Static type checking
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.18.2
    hooks:
      - id: mypy
        name: mypy
        additional_dependencies: ["pandas", "sqlalchemy", "python-dotenv", "fitparse"]
        args:
          - "--pretty"
          - "--show-error-codes"
          - "--ignore-missing-imports"
          - "--check-untyped-defs"
        exclude: ^(notebooks/|data/|models/|tests/)

  # 3) Pytest — Run tests using local environment
  - repo: local
    hooks:
      - id: pytest
        name: pytest
        entry: pytest
        language: system
        types: [python]
        pass_filenames: false
        args: ["--maxfail=1", "--disable-warnings", "-q"]
        exclude: ^(notebooks/|data/|models/)

  # 4) Hygiene
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
