[tool.ruff]
line-length = 100
target-version = "py313"
# Skip virtualenvs, data, notebooks, etc.
exclude = [
  ".venv",
  ".git",
  "data",
  "models",
  "notebooks",
  "**/*.ipynb",
  "**/.ipynb_checkpoints",
]

# ---- Lint rules ----
[tool.ruff.lint]
select = ["E", "F", "I", "UP", "B", "C4", "SIM", "PL"]
ignore = [
  "E203",
  "E501",     # long lines are fine
  "PLR2004",  # magic numbers for array shapes
  "SIM105",   # try/except simplification
  "SIM116",   # dict suggestion
  "SIM117",   # nested with suggestion
  "B904",     # raise ... from err
]

[tool.ruff.format]
quote-style = "preserve"
indent-style = "space"

# ---- Type checking ----
[tool.mypy]
python_version = "3.11"
warn_unused_configs = true
ignore_missing_imports = true
pretty = true
exclude = "^(notebooks/|data/|models/|tests/)"


# ---- Testing ----
[tool.pytest.ini_options]
addopts = "-v --maxfail=3 --disable-warnings"
testpaths = ["tests"]
python_files = ["test_*.py"]
